// "use client";

import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";

// import useAxiosAuth from "@/lib/hooks/useAxiosAuth";
// import { useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// dynamic metadata
// export async function generateMetadata() {
//   return {
//     title: "Hey you",
//   };
// }

export default async function Page() {
  const posts = await getPosts();
  //   const [score, setScore] = useState(0);
  //   const { value } = useThemeContext();
  //   const increaseScore = () => setScore(score + 1);
  // const data = useAxiosAuth().get("/auth");
  // const res = await
  return (
    <div>
      {/* {value} */}
      Blog
      <br />
      {JSON.stringify(posts)}
      {/* <p>Your score is {score}</p> */}
      {/* <button onClick={increaseScore}>+</button> */}
    </div>
  );
}

async function getPosts() {
  const session = await getServerSession(authOptions);
  return {
    session,
  };
  // const token = store.getState().auth.token;
  const res = await fetch(process.env.NEXT_PUBLIC_BASE_URL + "/setting/webInitialData", { next: { revalidate: 5 } });
  const data = await res.json();
  return data;
}
